site_name: Manual de Usuario Alumno – Edu 2.0

theme:
  name: material
  language: es
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - palette.toggle
    - navigation.sections
    - content.code.copy


extra_javascript:
  - js/logo-theme-switcher.js
markdown_extensions:
  - attr_list

plugins:
  - search
  - glightbox:
      touchNavigation: true
      effect: zoom
      zoomable: true
      draggable: true

nav:
  - Introducción: index.md
  - Acceso e inicio de sesión: acceso.md
  - Pantalla principal del alumno: principal.md
  - Consultas académicas : consultas.md
  - Gestión del chat y limpieza de historial: gestion_chat.md
  - Exámenes:
    - Acceso a exámenes disponibles: examenes_disponibles.md
    - Realización del examen: realizar_examen.md
    - Resultados y revisión: resultado_revision.md
    - Revisión de intentos anteriores: revison.md
  - Recomendaciones generales: recomendaciones.md
  - Cierre de sesión: cierre.md
  - Acerca de Smartech: acerca.md

dev_addr: 127.0.0.1:8001
